import Auth from '@aws-amplify/auth'
import { HubPayload } from '@aws-amplify/core'
import { DataStore, Hub } from 'aws-amplify'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import React, { useEffect, useState } from 'react'
import { Button } from 'react-bootstrap'
import { SignInOutButton } from '../src/components/LoginComponents/LoginPopover'
import { useAuth } from '../src/hooks/useCurrentUser'
import { Rider } from '../src/models'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {

    const [riderData, setRiderData] = useState<Rider>();
    
    

    const auth = useAuth();
    const {cognitoId,name, email, signedIn} = auth;

    //Sync listener for datastore, so we only query when we have fetched the data.  
    const [syncReady, setSyncReady] = useState(false);
    const listener = (data: {payload: HubPayload}) => {
        if(data.payload.event === 'ready') {
            console.log("sync ready")
            setSyncReady(true)
        }
    } 
    useEffect(()=> {
        Hub.listen('datastore', listener )
        return () => Hub.remove('datastore', listener)
    })


    //Query to get the rider data for the currenly logged in user.  
    useEffect(()=> {
        if(signedIn && cognitoId && syncReady){
            console.log(`Query for: ${cognitoId}`)   
            DataStore.query(Rider,r=>r.cognitoId('eq', cognitoId))
            .then(riders => {
                console.log(`saving riders: ${JSON.stringify(riders)}`)
                setRiderData(riders[0])

            }).catch(console.error);
        }else{
            setRiderData(undefined)
        }
        
    },[cognitoId, signedIn, syncReady])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <div className={styles.AuthDiv}>
          <SignInOutButton />
          <Link passHref href='create-account' >
            <Button variant='outline-info'className={styles.createAccountButton} >Create Account</Button>
          </Link>
          </div>
        <h1 className={styles.title}>
          Welcome to Steezy
        </h1>

        <div className={styles.description}>
            <p>
          UserId is {cognitoId}
          <br />
          Name is {name}
          <br />
          email is {email}
          </p>
          <hr />
          <div style={{fontSize: '20px'}}>
          User Object is: 
          <br />
          <pre style={{textAlign: "left", backgroundColor:'black', color: "white", fontSize: "16px"}}>
          {JSON.stringify(riderData,null,2)}
          </pre>
          </div>
        </div>
        
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export default Home
